# Generated by Django 4.1 on 2022-12-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, verbose_name='位置编号')),
                ('a_name', models.CharField(max_length=12, verbose_name='位置名称')),
                ('a_park', models.CharField(max_length=12, verbose_name='所属园区')),
            ],
            options={
                'verbose_name': '位置信息',
                'verbose_name_plural': '位置信息',
                'db_table': 'addr',
                'ordering': ['a_id'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='猫咪编号')),
                ('s_bool', models.IntegerField(choices=[(1, '已绝育'), (0, '未绝育')], verbose_name='绝育状态')),
                ('c_name', models.CharField(max_length=12, verbose_name='猫咪昵称')),
                ('c_sex', models.IntegerField(choices=[(1, '公'), (0, '母')], verbose_name='猫咪性别')),
                ('c_look', models.CharField(max_length=4, verbose_name='猫咪外貌')),
                ('c_icon', models.ImageField(blank=True, null=True, upload_to='images/cats', verbose_name='猫咪照片')),
                ('c_status', models.IntegerField(choices=[(2, '健康'), (1, '良好'), (0, '较差')], verbose_name='猫咪状态')),
                ('c_character', models.CharField(blank=True, max_length=12, null=True, verbose_name='猫咪性格')),
                ('c_first', models.DateField(verbose_name='首次目击')),
                ('c_recent', models.DateField(verbose_name='最近目击')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.addr', verbose_name='最近位置')),
            ],
            options={
                'verbose_name': '猫咪信息',
                'verbose_name_plural': '猫咪信息',
                'db_table': 'cat',
                'ordering': ['c_id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False, verbose_name='食品编号')),
                ('f_name', models.CharField(max_length=12, verbose_name='食品名称')),
            ],
            options={
                'verbose_name': '食品信息',
                'verbose_name_plural': '食品信息',
                'db_table': 'food',
                'ordering': ['f_id'],
            },
        ),
        migrations.CreateModel(
            name='Sterilize',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, verbose_name='绝育编号')),
                ('s_time', models.DateField(verbose_name='绝育日期')),
            ],
            options={
                'verbose_name': '绝育信息',
                'verbose_name_plural': '绝育信息',
                'db_table': 'sterilize',
                'ordering': ['s_id'],
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('u_name', models.CharField(max_length=12, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
                'ordering': ['u_id'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False, verbose_name='投喂编号')),
                ('t_time', models.DateField(verbose_name='投喂时间')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.addr', verbose_name='投喂位置')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.cat', verbose_name='投喂猫咪')),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.food', verbose_name='投喂食品')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.userinfo', verbose_name='投喂用户')),
            ],
            options={
                'verbose_name': '投喂信息',
                'verbose_name_plural': '投喂信息',
                'db_table': 'feed',
                'ordering': ['-t_id'],
            },
        ),
        migrations.CreateModel(
            name='Checkcat',
            fields=[
                ('k_id', models.AutoField(primary_key=True, serialize=False, verbose_name='打卡编号')),
                ('k_time', models.DateField(verbose_name='打卡时间')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.addr', verbose_name='打卡位置')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.cat', verbose_name='打卡猫咪')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cats.userinfo', verbose_name='打卡用户')),
            ],
            options={
                'verbose_name': '打卡信息',
                'verbose_name_plural': '打卡信息',
                'db_table': 'checkcat',
                'ordering': ['-k_id'],
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cats.sterilize', verbose_name='绝育编号'),
        ),
        migrations.CreateModel(
            name='CatRel',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关系编号')),
                ('r_type', models.IntegerField(choices=[(0, '父子'), (1, '母子'), (2, '兄弟'), (3, '姐妹'), (4, '朋友'), (5, '敌人')], verbose_name='关系类型')),
                ('c_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_1', to='cats.cat', verbose_name='猫咪1')),
                ('c_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_2', to='cats.cat', verbose_name='猫咪2')),
            ],
            options={
                'verbose_name': '关系信息',
                'verbose_name_plural': '关系信息',
                'db_table': 'cat_rel',
                'ordering': ['cr_id'],
                'unique_together': {('c_1', 'c_2')},
            },
        ),
    ]
