# Generated by Django 4.1 on 2022-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='c_sex',
            field=models.CharField(choices=[('公', '公'), ('母', '母')], max_length=10, verbose_name='猫咪性别'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='c_status',
            field=models.CharField(choices=[('健康', '健康'), ('良好', '良好'), ('较差', '较差')], max_length=10, verbose_name='猫咪状态'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='s_bool',
            field=models.CharField(choices=[('已绝育', '已绝育'), ('未绝育', '未绝育')], max_length=10, verbose_name='绝育状态'),
        ),
        migrations.AlterField(
            model_name='catrel',
            name='r_type',
            field=models.CharField(choices=[('父子', '父子'), ('母子', '母子'), ('兄弟', '兄弟'), ('姐妹', '姐妹'), ('朋友', '朋友'), ('敌人', '敌人')], max_length=10, verbose_name='关系类型'),
        ),
    ]
